DiscordBot.Server/Controllers/BotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DiscordBot.Server.Models;
using DiscordBot.Server.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using DiscordBot.Server.Resources.Constants;
using DiscordBot.Server.Twitch;
using Microsoft.EntityFrameworkCore;
using Abstractions;
using DiscordBot.LibraryData.Models;
using DiscordBot.Server.Controllers.Helpers;
using Abstractions.Db;
using DiscordBot.Server.Bot;
using DiscordBot.Server.Bot.Services;

namespace DiscordBot.Server.Controllers
{
    [Authorize(Policy = "AdminRolePolicy")]
    public class BotController : Controller
    {
        private readonly IGuildMessages _guildMessageManager;
        private readonly IGuildNotifications _guildNotificationsManager;
        private readonly ITwitchStreamers _streamersManager;
        private readonly IGuildBot _bot;
        private readonly ILogger _logger;
        private readonly BotEvents _botEvents;
        private readonly TwitchHelper _twitchHelper;
        private readonly ICommandHandler _commandHandler;
        private readonly ITwitchLiveMonitor _liveMonitor;
        private readonly IGuildRolesManager _guildRolesManager;

        public BotController(IGuildMessages guildMessageManager, IGuildNotifications guildNotificationsManager, ITwitchStreamers streamersManager,
            IGuildBot bot, ILogger logger, BotEvents botEvents, TwitchHelper twitchHelper, ICommandHandler commandHandler, 
            ITwitchLiveMonitor liveMonitor, IGuildRolesManager guildRolesManager)
        {
            _guildMessageManager = guildMessageManager;
            _guildNotificationsManager = guildNotificationsManager;
            _streamersManager = streamersManager;
            _bot = bot;
            _logger = logger;
            _botEvents = botEvents;
            _twitchHelper = twitchHelper;
            _commandHandler = commandHandler;
            _liveMonitor = liveMonitor;
            _guildRolesManager = guildRolesManager;
        }

        [HttpGet]
        public IActionResult Commands()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> EditStreamer(StreamerViewModel model)
        {
            var streamer = await _streamersManager.GetStreamerByUniqueId(model.UniqueID);

            try
            {
                if (streamer != null)
                {
                    var s = await _twitchHelper.GetStreamer(streamer.StreamerLogin);
                    streamer.StreamerLogin = model.StreamerLogin;
                    streamer.UrlAddress = model.Url;

                    if (s.Users.Length != 0)
                    {
                        streamer.StreamerId = s.Users[0].Id;
                    }

                    await _streamersManager.AddStreamerAsync(streamer);
                }
            }
            catch (DbUpdateException ex)
            {
                ViewBag.ErrorTitle = $"Database error!";
                ViewBag.ErrorMessage = $"Something went wrong. The attempt to save the streamer has failed";
                _logger.Log($"Database Error: {ex.Message} -- {ex.StackTrace}");
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditStreamer(string id)
        {
            var streamer = await _streamersManager.GetStreamerByUniqueId(id);

            if (streamer != null)
            {
                var model = new StreamerViewModel
                {
                    UniqueID = streamer.UniqueID,
                    StreamerLogin = streamer.StreamerLogin,
                    Url = streamer.UrlAddress
                };

                return View(model);
            }
            else
            {
                ViewBag.ErrorMessage = $"Something went wrong. It seems this streamer doesn't exist. ";
                return View("NotFound");
            }
        }

        [HttpPost]
        public async Task<IActionResult> DeleteStreamer(string id)
        {
            var streamer = await _streamersManager.GetStreamerByUniqueId(id);

            if (streamer is null)
            {
                ViewBag.ErrorMessage = $"No streamers found";
                return View("NotFound");
            }
            else
            {
                await _streamersManager.DeleteStreamerAsync(streamer);
            }

            return RedirectToAction("ManageStreamers");
        }

        [HttpPost]
        public async Task<IActionResult> AddStreamer(StreamerViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model != null)
                {
                    var dbModel = new StreamerDbModel
                    {
                        StreamerLogin = model.StreamerLogin,
                        UrlAddress = model.Url,
                        UniqueID = Guid.NewGuid().ToString()
                    };

                    var result = await _twitchHelper.GetAndMapStreamerDataAsync(dbModel);

                    if (result is null)
                    {
                        ViewBag.ErrorMessage("", "Cannot find given streamer.");
                        return View("NotFound");
                    }
                    else
                    {
                        ViewBag.Alert = true;
                        ViewBag.Success = true;

                        try
                        {
                            await _streamersManager.AddStreamerAsync(result);
                        }
                        catch (DbUpdateException)
                        {
                            ViewBag.Success = false;
                        }
                        if (_liveMonitor.IsEnabled())
                        {
                            await _liveMonitor.CheckNewChannelsToMonitor();
                        }
                    }
                }
                else
                {
                    ViewBag.ErrorMessage("Something went wrong. :(");
                    return View("NotFound");
                }
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult AddStreamer()
        {
            ViewBag.Alert = false;

            return View();
        }

        public async Task<IActionResult> StartBot()
        {
            try
            {
                if (_bot.IsRunning())
                {
                    return BadRequest("Bot is already running.");
                }

                await _commandHandler.InitializeAsync();
                await _guildRolesManager.InitializeAsync();
                await _bot.Connect();
                await _liveMonitor.StartLiveMonitor();
                await Task.Delay(50);
                return RedirectToAction("ManageBot");
            }
            catch (Exception ex)
            {
                _logger.Log($"Starting bot has failed: {ex.Message} {ex.Data} - {ex.StackTrace}");

                ViewBag.ErrorTitle = $"Houston we have a problem :/";
                ViewBag.ErrorMessage = $"Error Message: {ex.Message}" +
                    $"Stack trace: {ex.StackTrace}";
                return View("Error");
            }
        }

        public async Task<IActionResult> StopBot()
        {
            if (!_bot.IsRunning())
            {
                return BadRequest("Bot is not running.");
            }


            try
            {
                await _commandHandler.Clear();
                await _guildRolesManager.Clear();
                await _bot.Stop();
            }
            catch (Exception ex)
            {
                _logger.Log($"{ex.Message} - {ex.StackTrace}");
            }

            await Task.Delay(50);
            return RedirectToAction("ManageBot");
        }


        [HttpGet]
        public async Task<IActionResult> ManageStreamers()
        {
            var streamers = await _streamersManager.GetStreamers();
            var model = new List<StreamerViewModel>();
            try
            {
                if (streamers != null)
                {
                    List<Task<StreamerDbModel>> tasks = new List<Task<StreamerDbModel>>();
                    foreach (var streamer in streamers)
                    {
                        tasks.Add(Task.Run(() => _twitchHelper.GetMappedStreamerAsync(streamer)));
                    }

                    var result = await Task.WhenAll(tasks);
                    tasks.Clear();
                    foreach (var s in result)
                    {
                        model.Add(new StreamerViewModel
                        {
                            IsStreaming = s.IsStreaming,
                            //PlayedGame = s.PlayedGame,
                            ProfileImage = s.ProfileImage,
                            StreamerId = s.StreamerId,
                            StreamerLogin = s.StreamerLogin,
                            StreamTitle = s.StreamTitle,
                            //TotalFollows = s.TotalFollows,
                            //Viewers = s.Viewers,
                            //Url = s.UrlAddress,
                            LiveIndicator = Images.OnlineStatus,
                            UniqueID = s.UniqueID
                        });
                    }

                    //foreach (var streamer in streamers)
                    //{
                    //    var mappitoStrimero = await _twitchHelper.GetAndMapStreamerDataAsync(streamer);

                    //    if (mappitoStrimero.ProfileImage == null || mappitoStrimero.ProfileImage.Length == 0)
                    //    {
                    //        mappitoStrimero.ProfileImage = Images.TwitchDefaultPicture;
                    //    }

                    //    model.Add(new StreamerViewModel
                    //    {
                    //        IsStreaming = mappitoStrimero.IsStreaming,

DiscordBot.Server/Views/Shared/NotFound.cshtml
@{ 
    ViewData["Title"] = "Not Found";
}

<h1>@ViewBag.ErrorMessage</h1>

<a asp-action="index" asp-controller="home">
    Click here to navigate to the home page
</a>

DiscordBot.Server/Views/Shared/Success.cshtml
@{
    ViewData["Title"] = "Success";
}

<h3 class="text-success">@ViewBag.SuccessTitle</h3>
<h4 class="text-success">@ViewBag.SuccessMessage</h4>

DiscordBot.Server/Views/Shared/_Layout.cshtml
@inject SignInManager<IdentityUser> SignInManager


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GuildBot</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-validate/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-validate/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

        @*<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
            asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
            crossorigin="anonymous"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />*@
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Guild Bot</a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#layoutNavbarSupportedContent"
                    aria-controls="layoutNavbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="layoutNavbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item"><a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link">Home</a></li>
                    @*<li class="nav-item"><a asp-area="" asp-controller="Home" asp-action="Privacy" class="nav-link">Privacy</a></li>*@
                    @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin") || User.IsInRole("Super Admin"))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true">
                                Manage
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" asp-controller="Administration" asp-action="ListUsers">Users</a>
                                <a class="dropdown-item" asp-controller="Administration" asp-action="ListRoles">Roles</a>
                                <a class="dropdown-item" asp-controller="Bot" asp-action="ManageBot">Bot</a>
                                <a class="dropdown-item" asp-controller="Account" asp-action="ChangePassword">Password</a>
                            </div>
                        </li>

                        <li class="nav-item"><a asp-area="" asp-controller="Bot" asp-action="Log" class="nav-link">Logs</a></li>
                        <li class="nav-item"><a asp-area="" asp-controller="Bot" asp-action="Commands" class="nav-link">Commands</a></li>
                    }
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3" style="margin-top: 3%">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - GuildBot - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>