DiscordBot.Server/ViewModels/ManageBotViewModel.cs
using DiscordBot.Server.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DiscordBot.Server.ViewModels
{
    public class ManageBotViewModel
    {
    }
}

DiscordBot.Server/Controllers/BotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DiscordBot.Server.Models;
using DiscordBot.Server.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using DiscordBot.Server.Resources.Constants;
using DiscordBot.Server.Twitch;
using Microsoft.EntityFrameworkCore;
using Abstractions;
using DiscordBot.LibraryData.Models;
using DiscordBot.Server.Controllers.Helpers;
using Abstractions.Db;
using DiscordBot.Server.Bot;
using DiscordBot.Server.Bot.Services;

namespace DiscordBot.Server.Controllers
{
    [Authorize(Policy = "AdminRolePolicy")]
    public class BotController : Controller
    {
        private readonly IGuildMessages _guildMessageManager;
        private readonly IGuildNotifications _guildNotificationsManager;
        private readonly ITwitchStreamers _streamersManager;
        private readonly IGuildBot _bot;
        private readonly ILogger _logger;
        private readonly BotEvents _botEvents;
        private readonly TwitchHelper _twitchHelper;
        private readonly ICommandHandler _commandHandler;
        private readonly ITwitchLiveMonitor _liveMonitor;
        private readonly IGuildRolesManager _guildRolesManager;

        public BotController(IGuildMessages guildMessageManager, IGuildNotifications guildNotificationsManager, ITwitchStreamers streamersManager,
            IGuildBot bot, ILogger logger, BotEvents botEvents, TwitchHelper twitchHelper, ICommandHandler commandHandler, 
            ITwitchLiveMonitor liveMonitor, IGuildRolesManager guildRolesManager)
        {
            _guildMessageManager = guildMessageManager;
            _guildNotificationsManager = guildNotificationsManager;
            _streamersManager = streamersManager;
            _bot = bot;
            _logger = logger;
            _botEvents = botEvents;
            _twitchHelper = twitchHelper;
            _commandHandler = commandHandler;
            _liveMonitor = liveMonitor;
            _guildRolesManager = guildRolesManager;
        }

        [HttpGet]
        public IActionResult Commands()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> EditStreamer(StreamerViewModel model)
        {
            var streamer = await _streamersManager.GetStreamerByUniqueId(model.UniqueID);

            try
            {
                if (streamer != null)
                {
                    var s = await _twitchHelper.GetStreamer(streamer.StreamerLogin);
                    streamer.StreamerLogin = model.StreamerLogin;
                    streamer.UrlAddress = model.Url;

                    if (s.Users.Length != 0)
                    {
                        streamer.StreamerId = s.Users[0].Id;
                    }

                    await _streamersManager.AddStreamerAsync(streamer);
                }
            }
            catch (DbUpdateException ex)
            {
                ViewBag.ErrorTitle = $"Database error!";
                ViewBag.ErrorMessage = $"Something went wrong. The attempt to save the streamer has failed";
                _logger.Log($"Database Error: {ex.Message} -- {ex.StackTrace}");
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditStreamer(string id)
        {
            var streamer = await _streamersManager.GetStreamerByUniqueId(id);

            if (streamer != null)
            {
                var model = new StreamerViewModel
                {
                    UniqueID = streamer.UniqueID,
                    StreamerLogin = streamer.StreamerLogin,
                    Url = streamer.UrlAddress
                };

                return View(model);
            }
            else
            {
                ViewBag.ErrorMessage = $"Something went wrong. It seems this streamer doesn't exist. ";
                return View("NotFound");
            }
        }

        [HttpPost]
        public async Task<IActionResult> DeleteStreamer(string id)
        {
            var streamer = await _streamersManager.GetStreamerByUniqueId(id);

            if (streamer is null)
            {
                ViewBag.ErrorMessage = $"No streamers found";
                return View("NotFound");
            }
            else
            {
                await _streamersManager.DeleteStreamerAsync(streamer);
            }

            return RedirectToAction("ManageStreamers");
        }

        [HttpPost]
        public async Task<IActionResult> AddStreamer(StreamerViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model != null)
                {
                    var dbModel = new StreamerDbModel
                    {
                        StreamerLogin = model.StreamerLogin,
                        UrlAddress = model.Url,
                        UniqueID = Guid.NewGuid().ToString()
                    };

                    var result = await _twitchHelper.GetAndMapStreamerDataAsync(dbModel);

                    if (result is null)
                    {
                        ViewBag.ErrorMessage("", "Cannot find given streamer.");
                        return View("NotFound");
                    }
                    else
                    {
                        ViewBag.Alert = true;
                        ViewBag.Success = true;

                        try
                        {
                            await _streamersManager.AddStreamerAsync(result);
                        }
                        catch (DbUpdateException)
                        {
                            ViewBag.Success = false;
                        }
                        if (_liveMonitor.IsEnabled())
                        {
                            await _liveMonitor.CheckNewChannelsToMonitor();
                        }
                    }
                }
                else
                {
                    ViewBag.ErrorMessage("Something went wrong. :(");
                    return View("NotFound");
                }
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult AddStreamer()
        {
            ViewBag.Alert = false;

            return View();
        }

        public async Task<IActionResult> StartBot()
        {
            try
            {
                if (_bot.IsRunning())
                {
                    return BadRequest("Bot is already running.");
                }

                await _commandHandler.InitializeAsync();
                await _guildRolesManager.InitializeAsync();
                await _bot.Connect();
                await _liveMonitor.StartLiveMonitor();
                await Task.Delay(50);
                return RedirectToAction("ManageBot");
            }
            catch (Exception ex)
            {
                _logger.Log($"Starting bot has failed: {ex.Message} {ex.Data} - {ex.StackTrace}");

                ViewBag.ErrorTitle = $"Houston we have a problem :/";
                ViewBag.ErrorMessage = $"Error Message: {ex.Message}" +
                    $"Stack trace: {ex.StackTrace}";
                return View("Error");
            }
        }

        public async Task<IActionResult> StopBot()
        {
            if (!_bot.IsRunning())
            {
                return BadRequest("Bot is not running.");
            }


            try
            {
                await _commandHandler.Clear();
                await _guildRolesManager.Clear();
                await _bot.Stop();
            }
            catch (Exception ex)
            {
                _logger.Log($"{ex.Message} - {ex.StackTrace}");
            }

            await Task.Delay(50);
            return RedirectToAction("ManageBot");
        }


        [HttpGet]
        public async Task<IActionResult> ManageStreamers()
        {
            var streamers = await _streamersManager.GetStreamers();
            var model = new List<StreamerViewModel>();
            try
            {
                if (streamers != null)
                {
                    List<Task<StreamerDbModel>> tasks = new List<Task<StreamerDbModel>>();
                    foreach (var streamer in streamers)
                    {
                        tasks.Add(Task.Run(() => _twitchHelper.GetMappedStreamerAsync(streamer)));
                    }

                    var result = await Task.WhenAll(tasks);
                    tasks.Clear();
                    foreach (var s in result)
                    {
                        model.Add(new StreamerViewModel
                        {
                            IsStreaming = s.IsStreaming,
                            //PlayedGame = s.PlayedGame,
                            ProfileImage = s.ProfileImage,
                            StreamerId = s.StreamerId,
                            StreamerLogin = s.StreamerLogin,
                            StreamTitle = s.StreamTitle,
                            //TotalFollows = s.TotalFollows,
                            //Viewers = s.Viewers,
                            //Url = s.UrlAddress,
                            LiveIndicator = Images.OnlineStatus,
                            UniqueID = s.UniqueID
                        });
                    }

                    //foreach (var streamer in streamers)
                    //{
                    //    var mappitoStrimero = await _twitchHelper.GetAndMapStreamerDataAsync(streamer);

                    //    if (mappitoStrimero.ProfileImage == null || mappitoStrimero.ProfileImage.Length == 0)
                    //    {
                    //        mappitoStrimero.ProfileImage = Images.TwitchDefaultPicture;
                    //    }

                    //    model.Add(new StreamerViewModel
                    //    {
                    //        IsStreaming = mappitoStrimero.IsStreaming,

DiscordBot.Server/Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Abstractions;
using AutoMapper;
using DiscordBot.Server.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace DiscordBot.Server.Controllers
{
    public class ChatController : Controller
    {
        private readonly IGuildBot _bot;

        public ChatController(IGuildBot bot)
        {
            _bot = bot;
        }

        public IActionResult Global()
        {
            if (!_bot.IsRunning()) 
            { 
                return RedirectToAction("ManageBot", "Bot", new { value = true }); 
            }

            var model = new ChatViewModel
            {
                AvailableServers = _bot.GetAvailableServers().Select(Mapper.Map<ServerDetailViewModel>),
                MessageBuffer = new List<ChatMessageViewModel>()
            };

            return View(model);
        }

        [HttpGet("[controller]/[action]/{serverId}/{channelId}")]
        public async Task<IActionResult> Channel(ulong serverId, ulong channelId)
        {
            if (!_bot.IsRunning()) { return RedirectToAction("ManageBot", "Bot", true); }

            var model = new ChatViewModel
            {
                ActiveServer = Mapper.Map<ServerDetailViewModel>(_bot.GetServerDetailFromId(serverId)),
                ActiveChannel = Mapper.Map<TextChannelViewModel>(_bot.GetTextChannelDetailFromId(serverId, channelId)),
                AvailableServers = _bot.GetAvailableServers().Select(Mapper.Map<ServerDetailViewModel>),
                MessageBuffer = (await _bot.GetMessageBufferFor(serverId, channelId)).Select(Mapper.Map<ChatMessageViewModel>)
            };

            return View(model);
        }
    }
}

DiscordBot.Server/Views/Bot/AddStreamer.cshtml
@model StreamerViewModel
@{
    ViewData["Title"] = "Add Streamer";
}

<h1>Add Streamer</h1>

@if (ViewBag.Alert == true)
{
    @if (ViewBag.Success == true)
    {
        <div id="myAlert" class="alert alert-success" onshow="setTimeout()">
            <a href="#" class="close" data-dismiss="alert">&times;</a>
            <strong>Success! A new streamer has been added.</strong>
        </div>
    }
    else
    {
        <div id="myAlert" class="alert alert-danger" onshow="setTimeout()">
            <a href="#" class="close" data-dismiss="alert">&times;</a>
            <strong>Error! Streamer could not be added to the database. The request failed.</strong>
        </div>
    }
}


<div class="row">
    <div class="col-md-4">
        <form id="onSubmit" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StreamerLogin">Nickname</label>
                <input asp-for="StreamerLogin" class="form-control" placeholder="Streamer1337" onkeypress="handleSpace(event)" />
                <span asp-validation-for="StreamerLogin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Url">Url</label>
                <input asp-for="Url" class="form-control" placeholder="https://www.twitch.tv/Streamer1337" onkeypress="handleSpace(event)"/>
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
            <button id="btnSubmit" type="submit" class="btn btn-primary">Add</button>
            <a class="btn btn-danger" asp-action="ManageStreamers" asp-controller="Bot">Cancel</a>
        </form>
    </div>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>


<script type="text/javascript">
    //$(function () {

    //    $('#btnSubmit').click(function (e) {
    //        $('#myAlert').show('fade');

    //        setTimeout(function () {
    //            $('#myAlert').hide('fade');
    //        }, 2000);

    //    });

    //    $('#linkClose').click(function () {
    //        $('#myAlert').hide('fade');
    //    });
    //});


    //window.onload = function () {
    //    document.getElementById('#onSubmit').onsubmit = function () {

    //    }
    //}
    //function myfunction() {
    //    setTimeout
    //}

    function handleSpace(event) {
        //handling ie and other browser keycode
        var keyPressed = event.which || event.keyCode;

        //Handling whitespace
        //keycode of space is 32
        if (keyPressed == 32) {
            event.preventDefault();
            event.stopPropagation();
        }
    }


    setTimeout(function () {
        $('#myAlert').hide('fade');
    }, 3000);

</script>

DiscordBot.Server/Views/Bot/Commands.cshtml
@{
    ViewData["Title"] = "Commands";
}

<h4 style="margin-bottom: 2%">List of bot's commands</h4>
<div class="row justify-content-center">
    <div class="col-auto">
        <table class="table table-active table-bordered">
            <thead>
                <tr>
                    <th scope="col">Komenda</th>
                    <th scope="col">Opis</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>!pinned</td>
                    <td>Pokazuje wszystkie przypięte wiadomości na tym kanale.</td>
                </tr>
                <tr>
                    <td>!raidinfo</td>
                    <td>Wyświetla ustalony przed administratora komunikat dotyczący raidów.</td>
                </tr>
                <tr>
                    <td>!regulamin</td>
                    <td>Wyświetla regulamin gildii.</td>
                </tr>
                <tr>
                    <td>!progress</td>
                    <td>Wyświetla progress gildii z trzech ostatich tierów.</td>
                </tr>
                <tr>
                    <td>!recent</td>
                    <td>Wyświetla trzy ostatnio zrobione mplusy. Przykład: !recent nazwa_postaci realm region</td>
                </tr>
                <tr>
                    <td>!best</td>
                    <td>Wyświetla najlepsze zriobione klucze (od 1-5). Przykład: !best ToxicDzordzo kazzak eu 4</td>
                </tr>
                <tr>
                    <td>!charinfo</td>
                    <td>Wyświetla informacje o postaci (np: ilvl, mplus score, link do profilu na raider.io etc.) Przykład: !charinfo nazwa_postaci realm region.</td>
                </tr>
                <tr>
                    <td>!purge</td>
                    <td>Usuwa podaną liczbę wiadomości z discorda(max. 50) lub wiadomości podanego użytkownika. Przykład: !purge liczba_wiadomości lub !purge username#0000 (działa tagowanie z discorda @@Użytkownik).</td>
                </tr>
                <tr>
                    <td>!set_twitch</td>
                    <td>Ustawia kanał na którym mają pojawiać się powiadomienia o streamach.</td>
                </tr>
                <tr>
                    <td>!charinfo</td>
                    <td>Wyświetla informacje o postaci (np: ilvl, mplus score, link do profilu na raider.io etc.) Przykład: !charinfo nazwa_postaci realm region.</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

DiscordBot.Server/Views/Bot/EditGuildMessage.cshtml
@model GuildMessageViewModel

@{
    ViewData["Title"] = "Edit Message";
}


<h1>Edit Message</h1>

<form method="post" class="mt-3">
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">MessageId:</label>
        <div class="col-sm-10">
            <input asp-for="MessageId" disabled class="form-control">
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Message" class="col-sm-2 col-form-label">Message:</label>
        <div class="col-sm-10">
            @*<input asp-for="Message" class="form-control" />*@
            <textarea asp-for="Message" maxlength="2000" class="form-control" rows="5"></textarea>
            <span asp-validation-for="Message" class="text-danger"></span>
        </div>
    </div>
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary" asp-route-id="@Model.MessageId">Save</button>
            <a asp-action="ManageGuildMessages" class="btn btn-primary">Cancel</a>
        </div>
    </div>
</form>

DiscordBot.Server/Views/Bot/EditStreamer.cshtml
@model StreamerViewModel
@{
    ViewData["Title"] = "Edit Streamer";
}

<h1>Edit Streamer</h1>

<form method="post" class="mt-3">
    <div class="form-group row">
        <div class="col-sm-10">
            <input asp-for="UniqueID" type="hidden" class="form-control">
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="StreamerLogin" class="col-sm-2 col-form-label">Login:</label>
        <div class="col-sm-10">
            <input asp-for="StreamerLogin" class="form-control" onkeypress="handleSpace(event)"/>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Url" class="col-sm-2 col-form-label">URL:</label>
        <div class="col-sm-10">
            <input asp-for="Url" class="form-control" onkeypress="handleSpace(event)"/>
        </div>
    </div>
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Save</button>
            <a asp-action="ManageStreamers" class="btn btn-primary">Cancel</a>
        </div>
    </div>
</form>

<script type="text/javascript">
    function handleSpace(event) {
        //handling ie and other browser keycode
        var keyPressed = event.which || event.keyCode;

        //Handling whitespace
        //keycode of space is 32
        if (keyPressed == 32) {
            event.preventDefault();
            event.stopPropagation();
        }
    }

</script>

DiscordBot.Server/Views/Bot/Log.cshtml
@model IEnumerable<string>
@{
    ViewData["Title"] = "Log";
}

<div class="container-fluid">
    <div class="row">
        <h5>Full log (newest first)</h5>
        <div class="col-12 pre-scrollable" style="background-color:black; max-height: 500px; min-height:500px">

            <ul class="col-12 justify-content-center" id="LoggerWidgetList" style="list-style-type: none; margin-top:20px">
                @foreach (var message in Model)
                {
                    <li class="log-item"><i class="fas fa-angle-right"></i>@message</li>
                }
            </ul>
        </div>
    </div>
</div>

@section Scripts
{
    <script src="~/lib/@Html.Raw("@")aspnet/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/signalRConnection.js"></script>
    <script src="~/js/fullLoggerSignalR.js"></script>
    @*<script src="~/js/loggerSignalR.js"></script>*@
}

DiscordBot.Server/Views/Bot/ManageBot.cshtml
@inject SignInManager<IdentityUser> SignInManager

@{
    ViewData["Title"] = "Manage Bot";
    var isRunning = ViewBag.IsRunning;
}

@if (ViewBag.Alert == true)
{
    @if (isRunning == false)
    {
        <div id="myAlert" class="alert alert-danger" onshow="setTimeout()">
            <a href="#" class="close" data-dismiss="alert">&times;</a>
            <strong>Error! In order to launch Chat you must turn on the bot first.</strong>
        </div>
    }
}

<div class="row justify-content-center">
    <div class="col-12 text-center" style="margin:1% 0% 2% 0%">
        <span class="text-secondary"><strong>Bot is currently: </strong></span>
        @if (isRunning == true)
        {
            <span class="text-success"><strong>Online</strong></span>
        }
        else
        {
            <span class="text-danger"><strong>Offline</strong></span>
        }
    </div>
    <div class="col-auto">

        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin") || User.IsInRole("Super Admin"))
        {
            <h5 class="text-center" style="margin-bottom:10%">Launch Bot:</h5>
            @*<input class="btn btn-success" type="button" value="Start" onclick="location.href='@Url.Action("startbot", "Bot")'" />
            <input class="btn btn-danger" type="button" value="Stop" onclick="location.href='@Url.Action("stopbot", "Bot")'" />*@

            <a class="btn btn-success" asp-action="StartBot" asp-controller="Bot">Start</a>
            <a class="btn btn-danger" asp-action="StopBot" asp-controller="Bot">Stop</a>
            <a class="btn btn-secondary" asp-action="Global" asp-controller="Chat">Chat</a>
        }
    </div>
</div>
<br />
<h5 class="text-center">Manage:</h5>
<div class="row justify-content-center">

    <ul class="nav justify-content-center">
        <li class="nav-item">
            <a class="nav-link active" asp-action="ManageStreamers" asp-controller="Bot">Streamers</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-action="ManageGuildNotifications" asp-controller="Bot">Notifications</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-action="ManageGuildMessages" asp-controller="Bot">Messages</a>
        </li>
    </ul>
</div>


@section Scripts
{
    <script type="text/javascript">

        setTimeout(function () {
            $('#myAlert').hide('fade');
        }, 7000);

    </script>

}

DiscordBot.Server/Views/Bot/ManageGuildMessages.cshtml
@model List<GuildMessageViewModel>

@{
    ViewData["Title"] = "Manage Messages";
}


<div class="col-auto" style="margin:3% 0 1% 0">
    <a class="btn btn-primary" asp-action="ManageBot" asp-controller="Bot">Back</a>
</div>


@if (Model.Any())
{
    foreach (var msg in Model)
    {
        <div class="card mb-3">
            <div class="card-header">
                Message Id : @msg.MessageId
            </div>
            <div class="card-body">
                <p class="card-title">@msg.Message</p>
            </div>
            <div class="card-footer">
                <form method="get">
                    @if ((await authService.AuthorizeAsync(User, "ManageBotPolicy")).Succeeded)
                    {
                        <button type="submit" class="btn btn-primary" asp-action="EditGuildMessage" asp-controller="Bot" asp-route-id="@msg.MessageId">Edit</button>
                    }
                </form>
            </div>
        </div>
    }
}
else
{
    <div class="card">
        <div class="card-header">
            No messages yet
        </div>
        <div class="card-body">
            <h5 class="card-title">
                No data
            </h5>
        </div>
    </div>
}

DiscordBot.Server/Views/Bot/ManageGuildNotifications.cshtml
@model GuildNotificationViewModel

@{
    ViewData["Title"] = "Manage Notifications";
}

<!DOCTYPE html>

<div class="row justify-content-center">
    <div class="card-body col-6 mx-auto">
        <form method="post">
            <div class="card mb-4">
                <div class="card-body" style="margin-top: 5%">
                    <div class="form-check m-1 text-center">
                        <input type="hidden" asp-for="@Model.NotifyId" />
                        <input asp-for="@Model.Notify" class="form-check-input" />
                        <label class="form-check-label" asp-for="@Model.Notify">
                            Turn ON
                        </label>
                    </div>
                    <div asp-validation-summary="All" class="text-danger"></div>
                </div>
                <div class="card-body text-center">
                    <input type="submit" asp-action="ManageGuildNotifications" value="Save" class="btn btn-primary"
                           style="width:auto" />
                    <a asp-action="ManageBot" class="btn btn-danger">Back</a>
                </div>
            </div>
        </form>
    </div>
</div>

DiscordBot.Server/Views/Bot/ManageStreamers.cshtml
@model List<StreamerViewModel>

@{
    ViewData["Title"] = "Manage Streamers";
}

@*<style>
    #mdb-preloader.loaded {
        opacity: 0;
        transition: .5s ease-in 1s;
    }
</style>*@



<div class="col-auto" style="margin:3% 0 1% 0">
    <a class="btn btn-primary" asp-action="AddStreamer" asp-controller="Bot">Add Streamer</a>
    <a class="btn btn-primary" asp-action="ManageBot" asp-controller="Bot">Back</a>
</div>

@*<div id="mdb-preloader" class="flex-center">
    <div class="flex-wrap active">
        <div class="container h-auto d-flex justify-content-center align-items-center">
            <div id="loading" class="spinner-border align-items-center" style="width: 3rem; height: 3rem; margin-top:15%;" role="status"></div>
        </div>
    </div>
</div>*@

<table class="table table-hover">

    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Picture</th>
            <th scope="col">Login</th>
            <th scope="col">Stream Title</th>
            <th scope="col">Status</th>
            <th scope="col">Manage</th>
        </tr>
    </thead>

    <tbody class="tableBody col-auto">
        @for (int i = 0; i < Model.Count; i++)
        {
            <tr>
                <th scope="row">@(i + 1)</th>
                <td><a href="@Model[i].Url" target="_blank"><img class="d-block" src="@Model[i].ProfileImage" alt="#" style="max-width: 55px; min-width: 50px"/></a></td>
                <td>@Model[i].StreamerLogin</td>
                <td>@Model[i].StreamTitle</td>
                @if (@Model[i].IsStreaming == true)
                {
                    <td class="align-items-center"><img class="d-block mx-auto" style="margin-top:35%; filter:grayscale(0%)" id="" src="@Model[i].LiveIndicator" alt="Status" /></td>
                }
                else
                {
                    <td class="align-items-center"><img class="d-block mx-auto" style="margin-top:35%; filter:grayscale(95%)" id="" src="@Model[i].LiveIndicator" alt="Status" /></td>
                }
                <td>
                    <div class="dropdown" style="margin-top:17%;">
                        <a class="btn-sm btn-secondary dropdown-toggle align-items-center" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Action
                        </a>

                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <a class="dropdown-item" asp-action="EditStreamer" asp-route-id="@Model[i].UniqueID" asp-controller="Bot">Edit</a>

                            <button data-id="@Model[i].UniqueID" type="button" id="btnModal" class="dropdown-item" data-toggle="modal" data-target="#exampleModal">
                                Delete
                            </button>
                        </div>
                    </div>

                    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Wat?</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Are you sure you want to destroy this streamer?
                                </div>
                                <div class="modal-footer">
                                    <form asp-action="DeleteStreamer" asp-controller="Bot" method="post">
                                        <input type="hidden" data-id="" />
                                            @Html.Hidden("id", "", new { @class = "hiddenid" })
                                        <input type="submit" value="Yes" class="btn btn-danger" style="width:auto" />
                                    </form>
                                    <a class="btn btn-primary" data-dismiss="modal">No</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts
{
    <script type="text/javascript">
        $(".dropdown-item").click(function () {
            var passedID = $(this).data('id');  //get the id of the selected button
            $('.modal-footer .hiddenid').val(passedID);  //set the id to the input on the modal
        });


        //$(window).on('load', function () {
        //    $('#mdb-preloader').addClass('loaded');
        //});

        //window.onload = function () { document.getElementById("loading").style.display = "none" }
    </script>
}


@*<script language="javascript" type="text/javascript">
    window.onload = function () { document.getElementById("loading").style.display = "none" }
</script>*@